# Generated by Django 5.2.8 on 2026-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url2',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
