# Generated by Django 6.0.2 on 2026-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_banner_image_url_alter_category_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_url',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image_url2',
            new_name='image2',
        ),
    ]
