# Generated by Django 6.0.2 on 2026-05-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_image_url2_category_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='image_url',
            new_name='image',
        ),
    ]
