# Generated by Django 6.0.2 on 2026-03-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_remove_sellerprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
